services:
  db:
    image: postgres:15
    ports:
      - "5544:5432" # Maps host 55433 to container 5432
    restart: unless-stopped
    env_file:
      - ./.env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  web:
    build: ./backend
    restart: unless-stopped
    env_file:
      - ./.env
    environment:
      DJANGO_DB_HOST: db
      DJANGO_DB_NAME: ${POSTGRES_DB}
      DJANGO_DB_USER: ${POSTGRES_USER}
      DJANGO_DB_PASSWORD: ${POSTGRES_PASSWORD}
      DJANGO_DB_PORT: "5432"
    volumes:
      - static_volume:/app/staticfiles
    depends_on:
      db:
        condition: service_healthy
    expose:
      - "8000"
  
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VUE_APP_API_BASE_URL=${VUE_APP_API_BASE_URL} # Dynamically reads from your .env file
    command: npm run serve
    

  nginx:
    image: nginx:1.25-alpine
    restart: unless-stopped
    ports:
      - "8090:80"  # Changed to map Host 8090 to Container 80 (Assuming your default.conf listens on 80)
    volumes:
      - static_volume:/usr/share/nginx/html/static:ro
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:rw
    depends_on:
      - web
      - frontend

volumes:
  postgres_data:
  static_volume: