# Generated by Django 4.2.20 on 2025-05-19 05:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cheques', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PaymentInstrumentName',
            new_name='PaymentInstrument',
        ),
        migrations.AlterModelOptions(
            name='paymentinstrument',
            options={'verbose_name': 'Payment Instrument', 'verbose_name_plural': 'Payment Instruments'},
        ),
        migrations.RemoveField(
            model_name='paymentdetails',
            name='alias_id',
        ),
        migrations.RemoveField(
            model_name='paymentdetails',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='paymentdetails',
            name='payment_detail',
        ),
        migrations.RemoveField(
            model_name='paymentinstrumenttype',
            name='allow_multiple',
        ),
        migrations.AddField(
            model_name='paymentdetails',
            name='detail',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='paymentdetails',
            name='payment_instrument',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='cheques.paymentinstrument'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paymentdetails',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cheques.payment'),
        ),
        migrations.AlterModelTable(
            name='paymentinstrument',
            table='payment_instrument',
        ),
    ]
