# Generated by Django 4.2.20 on 2025-05-19 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheques', '0002_rename_paymentinstrumentname_paymentinstrument_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentdetails',
            name='is_adjusted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paymentinstrumenttype',
            name='is_cash_equialent',
            field=models.BooleanField(default=False),
        ),
    ]
