# Generated by Django 4.2.20 on 2025-05-19 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cheques', '0003_paymentdetails_is_adjusted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentdetails',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='paymentdetails',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='paymentdetails',
            name='version',
        ),
    ]
