# Generated by Django 4.2.20 on 2025-05-19 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cheques', '0004_remove_paymentdetails_updated_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentdetails',
            old_name='is_adjusted',
            new_name='is_allocated',
        ),
    ]
