# Generated by Django 4.2.20 on 2025-05-22 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cheques', '0005_rename_is_adjusted_paymentdetails_is_allocated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentinstrumenttype',
            old_name='is_cash_equialent',
            new_name='is_cash_equivalent',
        ),
        migrations.AlterField(
            model_name='paymentinstrument',
            name='instrument_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_type', to='cheques.paymentinstrumenttype'),
        ),
        migrations.AlterModelTable(
            name='paymentinstrumenttype',
            table='payment_instrument_type',
        ),
    ]
