# Generated by Django 4.2.20 on 2025-05-23 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheques', '0006_rename_is_cash_equialent_paymentinstrumenttype_is_cash_equivalent_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentinstrumenttype',
            old_name='next_number',
            new_name='last_number',
        ),
        migrations.AddField(
            model_name='paymentdetails',
            name='id_number',
            field=models.CharField(default='1', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentinstrumenttype',
            name='auto_number',
            field=models.BooleanField(default=False),
        ),
        
    ]
