# Generated by Django 4.2.20 on 2025-05-23 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cheques', '0007_rename_next_number_paymentinstrumenttype_last_number_and_more'),
    ]

    
