# Generated by Django 4.2.20 on 2025-05-23 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheques', '0008_remove_paymentdetails_unique_branch_id'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='paymentdetails',
            constraint=models.UniqueConstraint(fields=('branch', 'id_number'), name='unique_branch_id'),
        ),
    ]
