# Generated by Django 4.2.20 on 2025-05-27 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheques', '0010_alter_paymentdetails_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditinvoice',
            name='invoice_no',
        ),
        migrations.AddField(
            model_name='creditinvoice',
            name='grn',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paymentdetails',
            name='id_number',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
