# Generated by Django 4.2.20 on 2025-05-27 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheques', '0011_remove_creditinvoice_invoice_no_creditinvoice_grn_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='is_allocated',
            field=models.BooleanField(default=False),
        ),
    ]
