# Generated by Django 4.2.20 on 2025-05-28 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cheques', '0012_payment_is_allocated'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoicePaymentDetailMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocated_amount', models.DecimalField(decimal_places=4, max_digits=18)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cheques.branch')),
            ],
            options={
                'verbose_name': 'Invoice Payment Detail Map',
                'verbose_name_plural': 'Invoice Payment Detail Maps',
                'db_table': 'invoice_payment_detail_map',
            },
        ),
        migrations.RemoveField(
            model_name='customerclaim',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='customerclaim',
            name='claim',
        ),
        migrations.RemoveField(
            model_name='customerclaim',
            name='customer_payment',
        ),
        migrations.RemoveField(
            model_name='customerpayment',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='customerpayment',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='customerpayment',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='invoicechequemap',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='invoicechequemap',
            name='cheque_store',
        ),
        migrations.RemoveField(
            model_name='invoicechequemap',
            name='credit_invoice',
        ),
        migrations.RemoveField(
            model_name='invoiceclaimmap',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='invoiceclaimmap',
            name='credit_invoice',
        ),
        migrations.RemoveField(
            model_name='invoiceclaimmap',
            name='customer_claim',
        ),
        migrations.RemoveField(
            model_name='masterclaim',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='masterclaim',
            name='updated_by',
        ),
        migrations.AlterField(
            model_name='creditinvoice',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='ChequeStore',
        ),
        migrations.DeleteModel(
            name='CustomerClaim',
        ),
        migrations.DeleteModel(
            name='CustomerPayment',
        ),
        migrations.DeleteModel(
            name='InvoiceChequeMap',
        ),
        migrations.DeleteModel(
            name='InvoiceClaimMap',
        ),
        migrations.DeleteModel(
            name='MasterClaim',
        ),
        migrations.AddField(
            model_name='invoicepaymentdetailmap',
            name='credit_invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_allocations', to='cheques.creditinvoice'),
        ),
        migrations.AddField(
            model_name='invoicepaymentdetailmap',
            name='payment_detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_payments', to='cheques.paymentdetails'),
        ),
    ]
