# Generated by Django 4.2.20 on 2025-05-29 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cheques', '0013_invoicepaymentdetailmap_remove_customerclaim_branch_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentdetails',
            name='is_allocated',
        ),
    ]
