# Generated by Django 4.2.20 on 2025-05-29 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cheques', '0014_remove_paymentdetails_is_allocated'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentInvoiceMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cheques.branch')),
                ('credit_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='cheques.creditinvoice', unique=True)),
            ],
            options={
                'verbose_name': 'Payment Invoice Map',
                'verbose_name_plural': 'Payment Invoice Maps',
                'db_table': 'payment_invoice_map',
            },
        ),
        migrations.RemoveField(
            model_name='payment',
            name='is_allocated',
        ),
        migrations.AddField(
            model_name='payment',
            name='cash_equivalent_amount',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=18),
        ),
        migrations.AddField(
            model_name='payment',
            name='claim_amount',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=18),
        ),
        migrations.AddField(
            model_name='payment',
            name='sortage_amount',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=18),
        ),
        migrations.AddField(
            model_name='payment',
            name='total_amount',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=18),
        ),
        migrations.DeleteModel(
            name='InvoicePaymentDetailMap',
        ),
        migrations.AddField(
            model_name='paymentinvoicemap',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='cheques.payment'),
        ),
    ]
