# Generated by Django 4.2.20 on 2025-05-31 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cheques', '0016_creditinvoice_payment_delete_paymentinvoicemap'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='sortage_amount',
            new_name='shortage_amount',
        ),
        migrations.AlterField(
            model_name='creditinvoice',
            name='payment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice_set', to='cheques.payment'),
        ),
    ]
