# Generated by Django 4.2.20 on 2025-06-04 13:20

from django.db import migrations, models
import src.inve_lib.inve_lib


class Migration(migrations.Migration):
    def generate_unique_alias_ids(apps, schema_editor):
        PaymentDetails = apps.get_model('cheques', 'PaymentDetails')
        
        # Manually populate the alias_id field with unique values for existing records
        for payment_detail in PaymentDetails.objects.all():
            # If alias_id is empty or null, generate a unique value
            if not payment_detail.alias_id:
                # Create a unique value for alias_id (for example, using the primary key)
                payment_detail.alias_id = f"alias_{payment_detail.pk}"
                payment_detail.save()

    dependencies = [
        ('cheques', '0017_rename_sortage_amount_payment_shortage_amount_and_more'),
    ]

    operations = [
        
        migrations.AddField(
            model_name='paymentdetails',
            name='alias_id',
            field=models.TextField(default='', editable=True, max_length=10, unique=False),
        ),
        migrations.RunPython(generate_unique_alias_ids),
    ]
