# Generated by Django 4.2.20 on 2025-06-05 12:07

from django.db import migrations, models
import src.inve_lib.inve_lib


class Migration(migrations.Migration):

    dependencies = [
        ('cheques', '0018_paymentdetails_alias_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentdetails',
            name='alias_id',
            field=models.TextField(default=src.inve_lib.inve_lib.generate_slugify_id, editable=False, max_length=10, unique=True),
        ),
    ]
