# Generated by Django 4.2.20 on 2025-06-06 06:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import src.inve_lib.inve_lib


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cheques', '0019_alter_paymentdetails_alias_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias_id', models.TextField(default=src.inve_lib.inve_lib.generate_slugify_id, editable=False, max_length=10, unique=True)),
                ('submitted_date', models.DateField(null=True)),
                ('refund_amount', models.DecimalField(decimal_places=4, default=0.0, max_digits=18)),
                ('refund_date', models.DateField(null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.IntegerField(default=1)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cheques.branch')),
                ('payment_details', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_detail', to='cheques.paymentdetails')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Claim',
                'verbose_name_plural': 'Claims',
                'db_table': 'claim',
            },
        ),
    ]
