# Generated by Django 4.2.20 on 2025-06-06 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheques', '0020_claim'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
