# Generated by Django 4.2.20 on 2026-07-15 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cheques', '0021_claim_remarks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='creditinvoice',
            old_name='transaction_details',
            new_name='remarks',
        ),
    ]
