# Generated by Django 4.2.20 on 2026-07-17 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheques', '0022_rename_transaction_details_creditinvoice_remarks_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='creditinvoice',
            index=models.Index(fields=['transaction_date'], name='idx_ci_transaction_date'),
        ),
        migrations.AddIndex(
            model_name='creditinvoice',
            index=models.Index(fields=['branch', 'transaction_date'], name='idx_ci_branch_date'),
        ),
        migrations.AddIndex(
            model_name='creditinvoice',
            index=models.Index(fields=['customer', 'transaction_date'], name='idx_ci_customer_date'),
        ),
        migrations.AddIndex(
            model_name='creditinvoice',
            index=models.Index(fields=['payment', 'transaction_date'], name='idx_ci_payment_date'),
        ),
        migrations.AddIndex(
            model_name='creditinvoice',
            index=models.Index(fields=['-updated_at'], name='idx_ci_updated_at'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['parent'], name='idx_customer_parent_id'),
        ),
    ]
