# Generated by Django 4.2.20 on 2026-07-20 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheques', '0023_creditinvoice_idx_ci_transaction_date_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='paymentinstrument',
            constraint=models.UniqueConstraint(fields=('branch', 'serial_no'), name='unique_branch_serial_no'),
        ),
        migrations.AddConstraint(
            model_name='paymentinstrument',
            constraint=models.UniqueConstraint(fields=('branch', 'instrument_name'), name='unique_branch_instrument_name'),
        ),
    ]
