# Generated by Django 4.2.20 on 2026-07-17 11:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cheques', '0023_creditinvoice_idx_ci_transaction_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiKeyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_name', models.CharField(max_length=50, unique=True)),
                ('provider', models.CharField(choices=[('openrouter', 'OpenRouter'), ('google-ai-studio', 'Google AI Studio'), ('groq', 'Groq')], max_length=50)),
                ('api_key_hash', models.CharField(max_length=512)),
                ('base_url', models.CharField(blank=True, max_length=512, null=True)),
                ('model', models.CharField(blank=True, help_text="Model identifier, e.g. 'gemini-2.0-flash', 'gpt-4o'", max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'API Key Profile',
                'verbose_name_plural': 'API Key Profiles',
                'db_table': 'text_to_sql_api_key_profile',
            },
        ),
        migrations.CreateModel(
            name='TextToSqlLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('generated_sql', models.TextField(blank=True, null=True)),
                ('executed_sql', models.TextField(blank=True, null=True)),
                ('sql_params', models.JSONField(blank=True, null=True)),
                ('columns', models.JSONField(blank=True, null=True)),
                ('row_count', models.IntegerField(null=True)),
                ('execution_time_ms', models.IntegerField(null=True)),
                ('api_key_profile', models.CharField(blank=True, max_length=50, null=True)),
                ('llm_model', models.CharField(blank=True, max_length=100, null=True)),
                ('llm_provider', models.CharField(blank=True, max_length=50, null=True)),
                ('llm_tokens_used', models.IntegerField(null=True)),
                ('llm_cost_estimate', models.DecimalField(decimal_places=8, max_digits=12, null=True)),
                ('success', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cheques.branch')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Text-to-SQL Log',
                'verbose_name_plural': 'Text-to-SQL Logs',
                'db_table': 'text_to_sql_log',
                'indexes': [models.Index(fields=['user', '-created_at'], name='text_to_sql_user_id_06c486_idx'), models.Index(fields=['branch', '-created_at'], name='text_to_sql_branch__cf1df2_idx'), models.Index(fields=['-created_at'], name='text_to_sql_created_e35026_idx')],
            },
        ),
    ]
